using System;
using System.Collections.Generic;

namespace TrainDotNetCore.Models
{
    public partial class Item
    {
        public decimal Id { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string Status { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? Version { get; set; }
        public double? Areafg { get; set; }
        public double? BdLength { get; set; }
        public double? BdWidth { get; set; }
        public string BlockNumber { get; set; }
        public int? BomMapNumber { get; set; }
        public int? BoxPerBundle { get; set; }
        public int? BoxPerPallet { get; set; }
        public int? BundlePerLayer { get; set; }
        public string ColorFullString { get; set; }
        public double? DdHeight { get; set; }
        public double? DdLength { get; set; }
        public double? DdWidth { get; set; }
        public int? DisplayDuration { get; set; }
        public double? DisplayLoadCapacity { get; set; }
        public int? DisplayMoq { get; set; }
        public string DisplayRemarks { get; set; }
        public string DisplaySpecialCondition { get; set; }
        public double? DisplayTargetPrice { get; set; }
        public DateTime? DueDate { get; set; }
        public double? FgSheetLength { get; set; }
        public double? FgSheetWidth { get; set; }
        public string FilmSpec { get; set; }
        public int? FissureNum { get; set; }
        public string FlagAssembly { get; set; }
        public string FlagAutoSortColor { get; set; }
        public string FlagChangeProduct { get; set; }
        public string FlagJoinWidth { get; set; }
        public string FlagTwoPiecePerSet { get; set; }
        public string FlagWithoutSlit { get; set; }
        public int? FlexibleMoq { get; set; }
        public string FlexibleRemarks { get; set; }
        public double? FlexibleTargetPrice { get; set; }
        public double? GrossWeight { get; set; }
        public double? IdHeight { get; set; }
        public double? IdLength { get; set; }
        public double? IdWidth { get; set; }
        public string ItemCode { get; set; }
        public double? JoinSize { get; set; }
        public int? JoinSizeAdjust { get; set; }
        public int? LayerPerPallet { get; set; }
        public string MaterialDescription { get; set; }
        public string MaterialNumber { get; set; }
        public int? NumColor { get; set; }
        public int? NumColorDisplay { get; set; }
        public int? NumColorFlex { get; set; }
        public int? NumberOfCut { get; set; }
        public double? OdHeight { get; set; }
        public double? OdLength { get; set; }
        public double? OdWidth { get; set; }
        public double? OverHangLength { get; set; }
        public double? OverHangWidth { get; set; }
        public double? PalletHeight { get; set; }
        public int? PalletImgSelected { get; set; }
        public double? PalletLength { get; set; }
        public string PalletLoadCapacity { get; set; }
        public string PalletLoadType { get; set; }
        public int? PalletMoq { get; set; }
        public string PalletRemarks { get; set; }
        public string PalletSpecialCondition { get; set; }
        public int? PalletStackingLayerOther { get; set; }
        public double? PalletTargetPrice { get; set; }
        public double? PalletWidth { get; set; }
        public string PartNumber { get; set; }
        public string PcCodePrefix { get; set; }
        public string PcCodeRunning { get; set; }
        public string PcCodeSuffix { get; set; }
        public double? PdHeight { get; set; }
        public double? PdLength { get; set; }
        public double? PdWidth { get; set; }
        public int? PiecePerSet { get; set; }
        public string PlateNumber { get; set; }
        public double? PriceBahtPerTon { get; set; }
        public double? PriceBahtPerTonProductionPlant { get; set; }
        public double? PricePerPiece { get; set; }
        public double? PricePerPieceProductionPlant { get; set; }
        public DateTime? ProductCreateDate { get; set; }
        public DateTime? ProductLastUpdate { get; set; }
        public string ProductionPlan { get; set; }
        public string ProductionPlantDetail { get; set; }
        public int? QuantityPerPack { get; set; }
        public DateTime? ReleaseDate { get; set; }
        public string Remark { get; set; }
        public string SaleText { get; set; }
        public double? SdHeight { get; set; }
        public double? SdLength { get; set; }
        public double? SdWidth { get; set; }
        public int? StackingLayer { get; set; }
        public int? StaplerNum { get; set; }
        public string TagWord { get; set; }
        public double? ThicknessOfFilm { get; set; }
        public int? TransportationDuration { get; set; }
        public double? TrimWaste { get; set; }
        public double? TrimWastePercentage { get; set; }
        public double? VendorPrice { get; set; }
        public double? WeightPerUnit { get; set; }
        public decimal? Assembly { get; set; }
        public decimal? BagType { get; set; }
        public decimal? BoardCombination { get; set; }
        public decimal? BundlePerPallet { get; set; }
        public decimal? Coating { get; set; }
        public decimal? CorrugatingProcess { get; set; }
        public decimal? Customer { get; set; }
        public decimal? DestinationCountry { get; set; }
        public decimal? DisplayArea { get; set; }
        public decimal? DisplayPackingType { get; set; }
        public decimal? DisplayStackingLayer { get; set; }
        public decimal? FlexibleOtherFunction { get; set; }
        public decimal? FlexiblePackingType { get; set; }
        public decimal? Flute { get; set; }
        public decimal? HandlingType { get; set; }
        public decimal? Industry { get; set; }
        public decimal? ItemStatus { get; set; }
        public decimal? ItemType { get; set; }
        public decimal? JointType { get; set; }
        public decimal? MerchandisingDisplayMaterialType { get; set; }
        public decimal? MerchandisingDisplayType { get; set; }
        public decimal? OrderPlant { get; set; }
        public decimal? PackingMethod { get; set; }
        public decimal? Pallet { get; set; }
        public decimal? PalletMaterialType { get; set; }
        public decimal? PalletPackingType { get; set; }
        public decimal? PalletStackingLayer { get; set; }
        public decimal? PalletType { get; set; }
        public decimal? Plant { get; set; }
        public decimal? PrimaryPackaging { get; set; }
        public decimal? PrintMethod { get; set; }
        public decimal? PrintingTechnology { get; set; }
        public decimal? PrintingTechnologyDisplay { get; set; }
        public decimal? PrintingTechnologyFlex { get; set; }
        public decimal? ProductGroup { get; set; }
        public decimal? ProductSubType { get; set; }
        public decimal? ProductType { get; set; }
        public decimal? PsmCluster { get; set; }
        public decimal? RequestStatusArtwork { get; set; }
        public decimal? RequestStatusDrawing { get; set; }
        public decimal? SecondaryPackaging { get; set; }
        public decimal? ShelfLife { get; set; }
        public decimal? RequestStatus { get; set; }
        public decimal? TransportCondition { get; set; }
        public decimal? TransportationType { get; set; }
        public decimal? UsageConditions { get; set; }
        public string BomMatNumber { get; set; }
        public string ColorShadeFullString { get; set; }
        public string ProductionPlantStatus { get; set; }
        public int? JointLap { get; set; }
        public double? ScoreLinel2 { get; set; }
        public double? ScoreLinel3 { get; set; }
        public double? ScoreLinel4 { get; set; }
        public double? ScoreLinel5 { get; set; }
        public double? ScoreLinel6 { get; set; }
        public double? ScoreLinel7 { get; set; }
        public double? ScoreLinel8 { get; set; }
        public double? ScoreLinel9 { get; set; }
        public double? ScoreLinew1 { get; set; }
        public double? ScoreLinew2 { get; set; }
        public double? ScoreLinew3 { get; set; }
        public double? WeightPerUnitInsight { get; set; }
        public string PaperWidth { get; set; }
        public string OrderUser { get; set; }
        public string FlagOutterJoint { get; set; }
        public string BlockNumberFromCopy { get; set; }
        public decimal? CopyFrom { get; set; }
        public DateTime? LastEffectCostDate { get; set; }
        public int? VersionUpdateItemSpec { get; set; }
        public decimal? BlockType { get; set; }
        public double? PricePerPieceProd { get; set; }
        public int? Slit { get; set; }
        public string FullSaleText { get; set; }
        public double? MultiItemContribute { get; set; }
        public double? MultiItemSellingPrice { get; set; }
        public string MultiItemUploadRunning { get; set; }
        public double? MultiItemSequence { get; set; }
        public string FlagMulti { get; set; }
        public string MultiRunning { get; set; }
        public int? MultiUploadSequence { get; set; }
        public string Contbpcs { get; set; }
        public string Contbt { get; set; }
        public string Costbpcs { get; set; }
        public string LpStatus { get; set; }
        public string MultiLpGroup { get; set; }
        public string MultiLpMarkUp { get; set; }
        public string PrintingAround2 { get; set; }
        public string PrintingSolid3 { get; set; }
        public string Sellingbpcs { get; set; }
        public string Sellingbt { get; set; }
        public string Marginbt { get; set; }
        public string Contbm { get; set; }
        public string Marginbm { get; set; }
        public string Marginbp { get; set; }
        public string MultilppercentMargin { get; set; }
        public string Sellingbm { get; set; }
        public string SetNumber { get; set; }
        public string CpOther { get; set; }
        public string CpPrintLayout { get; set; }
        public string CpRemark { get; set; }
        public string ItemRefer { get; set; }
        public string OldChangeDetail { get; set; }
        public string LpInput { get; set; }
    }
}